### ISSUE TITLE
obj import assimp missing 3.8.0 Prerelease4

### ISSUE THREAD

**Issue by gpaar** [vrvis/PRo3D#69]
[fairly new PC & windows installation]

3: creating kdtree #0 of 1
 3: [OBJ] Please wait while the OBJ file is being loaded.
 3: ERROR
 3:   [media] update function failed with: Assimp.AssimpException: Error loading unmanaged library from path: C:\Users\charl\AppData\Local\Temp\aardvark-native\AssimpNet-969d1624-35de-e8ae-f27b-d0ea28a223a6-64\Assimp64.dll, see inner exception for details.
 3:   Das angegebene Modul wurde nicht gefunden. (0x8007007E)
 3:    ---> System.IO.FileNotFoundException: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
 3:      --- End of inner exception stack trace ---
 3:      at Assimp.Unmanaged.AssimpLibraryWindowsImplementation.NativeLoadLibrary(String path)
 3:      at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
 3:      at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
 3:      at Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded()
 3:      at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
 3:      at Assimp.AssimpContext.CreateConfigs()
 3:      at Assimp.AssimpContext.PrepareImport()
 3:      at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
 3:      at Aardvark.SceneGraph.IO.Loader.AssimpModule.loadFrom(String file, PostProcessSteps postProcessingFlags)
 3:      at PRo3D.Core.Surface.SurfaceUtils.ObjectFiles.loadObject(Surface surface)
 3:      at PRo3D.Core.Surface.SurfaceUtils.ObjectFiles.sghs@175-5.Invoke(Surface surface)
 3:      at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in E:\A\_work\130\s\src\fsharp\FSharp.Core\local.fs:line 249
 3:      at PRo3D.Core.Surface.SurfaceUtils.ObjectFiles.createSgObjects[a,b](a _arg2, b _arg1, IndexList`1 surfaces)
 3:      at PRo3D.SceneLoaderModule.importObj(IRuntime runtime, IFramebufferSignature signature, IndexList`1 surfaces, Model m)
 3:      at PRo3D.ViewerApp.update$cont@433-5(IRuntime runtime, IFramebufferSignature signature, BlockingCollection`1 sendQueue, FSharpMailboxProcessor`1 mailbox, Model m, ViewerAction msg, Boolean matchValue_2, Unit unitVar)
 3:      at <StartupCode$Aardvark-UI>.$App.doit@72-2.Invoke(Unit unitVar0)
[OPC] count = 53

**Comment by haraldsteinlechner** [comment]
@aszabo314 @krauthaufen @hyazinthh We see this in other applications as well, thank you @gpaar.

**Comment by haraldsteinlechner** [comment]
@gpaar The current development version got rid of this problem temporary (new build of external lib), but we we need to come back to this issue again since the object loading lib is rather outdated. anyways - chances are good that with installing https://www.microsoft.com/de-at/download/details.aspx?id=30679 your current problem goes away. if not, and running pro3d on this machine is urgend, we can create a fresh build out ouf development for that purpose - or we wait for the next release which will fix it definitely.

**Comment by gpaar** [comment]
Thx - I installed the 30679 but no remedy. It's not immediately urgent for me as I'm now using the scale bar feature which is sufficient for my current needs. Nevertheless in the forthcoming delivery it shall be clean if it's being deployed to a larger community. Thanks!

**Comment by haraldsteinlechner** [comment]
new assimp build, also needed by https://github.com/pro3d-space/PRo3D/issues/68 fixes this one. currently we are discussing the release plan...

**Comment by haraldsteinlechner** [comment]
seems that this one was fixed in pro3d 4.0. if you experience problems, please reopen again
